### PR TITLE
haml-lint changed name to haml_lint, Fixes #58

### LINKED ISSUE #58: haml-lint changed name to haml_lint
Hey!
https://github.com/brigade/haml-lint/commit/6bbe2d2f4938a41f77b270488c73015fc89f7631

I think its the cause why my CI machine raises:

```bash
Gem::RemoteFetcher::FetchError: bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/gems/haml-lint-0.13.0.gem)
An error occurred while installing haml-lint (0.13.0), and Bundler cannot
continue.
Make sure that `gem install haml-lint -v '0.13.0'` succeeds before bundling.
```
when try to install polishgeeks-dev-tools

### PR DESCRIPTION
**Pull request by agwozdowski**
Hi @nijikon, we need this fix quickly :)

### CODE REVIEW

**Comment by pavlo-vavruk** [comment]
:+1:

**Comment by nijikon** [comment]
I'm not gonna merge this as you changed the version of the release.

**Comment by pavlo-vavruk** [comment]
@nijikon will you fix it, or should we create the same PR but without version change?

**Comment by nijikon** [comment]
Releasing new version now.

**Comment by agwozdowski** [comment]
@nijikon I don't understand why I shouldn't change the version of the release?

**Comment by nijikon** [comment]
New release should not be in the same commit message as haml-lint change.

**Comment by agwozdowski** [comment]
@nijikon Ok, I understand. So, we are waiting for new version.

**Comment by nijikon** [comment]
15 minutes :)

**Pull request closed without merging**
